### ISSUE TITLE
ValueError: Unknown CUDA arch (8.6) or GPU not supported & RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by han1222** [SysCV/qd-3dt#25]
My laptop env is

NVIDIA RTX 3080
cuda 11.1
NVIDIA Driver Version: 470.57.02

when I run bash install.sh
with after pip install -r requriement.txt

1. 
ValueError: Unknown CUDA arch (8.6) or GPU not supported

so I installed cuda 11.1 pytorch version.

2.

pytorch with cuda 11.1 
when I run bash install.sh
then I got this error 

Traceback (most recent call last):
  File "setup.py", line 200, in <module>
    zip_safe=False)
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/han/anaconda3/envs/3dt/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by LawrenceXu13467** [comment]
Hi han1222,

By any chance have you solved this issue? Would you please share how you solved the issue?
I am having the same situation with "ValueError: Unknown CUDA arch (8.6) or GPU not supported" on 
RTX 3090
torch 1.8.0
cuda 11.3

Thank you very much.

Sincerely,
Ziheng

**Comment by han1222** [comment]
I haven't solved the problem yet

**Comment by alfinnurhalim** [comment]
Hi, did you solve it?

**Comment by gopaHB** [comment]
ValueError: Unknown CUDA arch (8.6) or GPU not supported
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by gopaHB** [comment]
How to solve it

**Comment by RoyYang0714** [comment]
Dear all, we now update the code and will be able to run on the newer hardware and the PyTorch version. Please check our [new prerequisites](https://github.com/SysCV/qd-3dt/blob/main/readme/INSTALL.md#new-prerequisites). Thanks!
