### ISSUE TITLE
Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by hahakid** [SysCV/qd-3dt#3]
I installed the project follows the instructions and prepared the KITTI data only. Pre-trained weights are placed in related folders.
When I try test mode with the below script:
./scripts/test_eval_exp.sh kitti configs/KITTI/quasi_dla34_dcn_3dmatch_multibranch_conv_dep_dim_cen_clsrot_sep_aug_confidence_subtrain_mod_anchor_ratio_small_strides_GTA.py 0 1 --data_split_prefix subval_dla34_regress_GTA_VeloLSTM --add_ablation_exp all 

but got the following error:

Traceback (most recent call last):
  File "./tools/test_eval_video_exp.py", line 10, in <module>
    from qd3dt.datasets import build_dataloader, build_dataset
  File "/home/kid/workspace/qd-3dt/qd3dt/datasets/__init__.py", line 1, in <module>
    from .custom import CustomDataset
  File "/home/kid/workspace/qd-3dt/qd3dt/datasets/custom.py", line 12, in <module>
    from .extra_aug import ExtraAugmentation
  File "/home/kid/workspace/qd-3dt/qd3dt/datasets/extra_aug.py", line 5, in <module>
    from qd3dt.core.evaluation.bbox_overlaps import bbox_overlaps
  File "/home/kid/workspace/qd-3dt/qd3dt/core/__init__.py", line 3, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/home/kid/workspace/qd-3dt/qd3dt/core/evaluation/__init__.py", line 4, in <module>
    from .coco_utils import coco_eval, fast_eval_recall, results2json
  File "/home/kid/workspace/qd-3dt/qd3dt/core/evaluation/coco_utils.py", line 3, in <module>
    from pycocotools.coco import COCO
  File "/home/kid/anaconda3/envs/3dt/lib/python3.7/site-packages/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/kid/anaconda3/envs/3dt/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

My environment is ubuntu18, but I think it is not related to the system version.

**Comment by hahakid** [comment]
> Could you try to re-install numpy?
> 
> ```
> pip uninstall numpy
> pip install numpy
> ```

I update the numpy and face another limitation problem:


Traceback (most recent call last):
  File "./tools/test_eval_video_exp.py", line 10, in <module>
    from qd3dt.datasets import build_dataloader, build_dataset
  File "/home/kid/workspace/qd-3dt/qd3dt/datasets/__init__.py", line 3, in <module>
    from .loader import GroupSampler, DistributedGroupSampler, build_dataloader
  File "/home/kid/workspace/qd-3dt/qd3dt/datasets/loader/__init__.py", line 1, in <module>
    from .build_loader import build_dataloader
  File "/home/kid/workspace/qd-3dt/qd3dt/datasets/loader/build_loader.py", line 15, in <module>
    resource.setrlimit(resource.RLIMIT_NOFILE, (65535, rlimit[1]))
ValueError: current limit exceeds maximum limit

I will try it myself.

**Comment by RoyYang0714** [comment]
The open file limit may cause this error. It seems that your machine does not support 65535 as the open file limit. You can try the smaller number to run the inference code. If you want to train the model your own for a larger dataset like GTA and Waymo, you may still need a larger open file limit for it.

**Comment by hahakid** [comment]
> The open file limit may cause this error. It seems that your machine does not support 65535 as the open file limit. You can try the smaller number to run the inference code. If you want to train the model your own for a larger dataset like GTA and Waymo, you may still need a larger open file limit for it.

I resized the num to 3000,  it works, but still got some other problems !_！
