### ISSUE TITLE
bash install.sh error

### ISSUE THREAD

**Issue by indigopyj** [SysCV/qd-3dt#39]
```
qd-3dt/qd3dt/ops/roi_align/src/roi_align_kernel.cu:3:10: fatal error: ATen/cuda/Atomic.cuh: No such file or directory
 #include <ATen/cuda/Atomic.cuh>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1672, in _run_ninja_build
    env=env)
  File "/home/user/anaconda3/envs/qdt_cuda11/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

```

I've got error from insalling, following your new requirements(torch 1.12.0).
Do you know any solution?

**Comment by JerryPW** [comment]
Hi, I got the same question. Have you figured it out?

**Comment by RoyYang0714** [comment]
Hi, you can try our newer version here: https://github.com/SysCV/vis4d/tree/main/vis4d/zoo/cc_3dt

**Comment by BaophanN** [comment]
how to fix this error
